import type { Metadata } from "next";
import { Footer, Navbar } from "@/components";
import "./globals.css";

export const metadata: Metadata = {
  title: "TravelShi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className="relative overflow-hidden">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
